config/routes.rb
Rails.application.routes.draw do
  resources :hotel_groups
  resources :hotels
  devise_for :users
  root "hotel_groups#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :hotel_group
  has_many :rooms, inverse_of: :hotel, dependent: :destroy
  accepts_nested_attributes_for :rooms, reject_if: :all_blank, allow_destroy: true
end

app/models/hotel_group.rb
class HotelGroup < ApplicationRecord
	has_many :hotels, dependent: :destroy
  has_many :hotels, inverse_of: :hotel_group, dependent: :destroy
  accepts_nested_attributes_for :hotels, reject_if: :all_blank, allow_destroy: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/hotel_groups_controller.rb
class HotelGroupsController < ApplicationController
  before_action :set_hotel_group, only: %i[ show edit update destroy ]

  # GET /hotel_groups or /hotel_groups.json
  def index
    @hotel_groups = HotelGroup.all
  end

  # GET /hotel_groups/1 or /hotel_groups/1.json
  def show
  end

  # GET /hotel_groups/new
  def new
    @hotel_group = HotelGroup.new
    @hotel_group.hotels.build
  end

  # GET /hotel_groups/1/edit
  def edit
    @hotel_group.hotels.build
  end

  # POST /hotel_groups or /hotel_groups.json
  def create
    @hotel_group = HotelGroup.new(hotel_group_params)

    respond_to do |format|
      if @hotel_group.save
        format.html { redirect_to hotel_group_url(@hotel_group), notice: "Hotel group was successfully created." }
        format.json { render :show, status: :created, location: @hotel_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotel_groups/1 or /hotel_groups/1.json
  def update
    respond_to do |format|
      if @hotel_group.update(hotel_group_params)
        format.html { redirect_to hotel_group_url(@hotel_group), notice: "Hotel group was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_groups/1 or /hotel_groups/1.json
  def destroy
    @hotel_group.destroy

    respond_to do |format|
      format.html { redirect_to hotel_groups_url, notice: "Hotel group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_group
      @hotel_group = HotelGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_group_params
      params.require(:hotel_group).permit(:name, hotels_attributes: Hotel.attribute_names.map(&:to_sym).push(:_destroy, :_id))
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  def index
    @hotels = Hotel.all
  end

  def show
  end

  def new
    @hotel = Hotel.new
    @hotel.rooms.build
  end

  def edit
    #@hotel.rooms.build
  end

  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: " Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotel_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, rooms_attributes: Room.attribute_names.map(&:to_sym).push(:_destroy, :_id))
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
    @room.rooms.build
  end

  def edit
    @room.rooms.build
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: " Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to room_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, hotels_attributes: Hotel.attribute_names.map(&:to_sym).push(:_destroy, :_id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotel_groups_helper.rb
module HotelGroupsHelper
end

app/helpers/hotel_helper.rb
module HotelHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/hotel_groups/_form.html.erb
<%= simple_form_for(@hotel_group) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Hotel Group Name') %>
  </div>
  <hr style="border: 1px solid;">
  <div class='builder'>
    <%= f.simple_fields_for :hotels do |builder| %>
          <%= render 'hotel', f: builder %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= link_to_add_association('Add hotel', f, :hotels, class: "btn btn-warning btn-sm") %>
  </div>
  <hr>
  <div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-lg pull-right" %>
  </div>
<% end %>

app/views/hotel_groups/_hotel.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-12">
      <div class="full-height-scroll">
        <div class="table-responsive">
          <table class="table table-striped" style="margin-bottom: 0;">
            <thead>
            <tr class="table-head">
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Hotel Name') %></td>
                <td><%= link_to_remove_association "Remove Hotel", f, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hotel_groups/_hotel_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-12">
      <div class="full-height-scroll">
        <div class="table-responsive">
          <table class="table table-striped" style="margin-bottom: 0;">
            <thead>
            <tr class="table-head">
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Hotel Name') %></td>
                <td><%= link_to_remove_association "Remove Hotel", f, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hotel_groups/_hotel_group.html.erb
<div id="<%= dom_id hotel_group %>">
  <p>
    <strong>Name:</strong>
    <%= hotel_group.name %>
  </p>
  <p>
    <strong>Hotels:</strong>
    <% hotel_group.hotels.each do |hotel| %>
      <%= link_to hotel.name, hotel_path(hotel) %>
    <% end %>
  </p>

</div>

app/views/hotel_groups/edit.html.erb
<h1>Editing hotel group</h1>

<%= render "form", hotel_group: @hotel_group %>

<br>

<div>
  <%= link_to "Show this hotel group", @hotel_group %> |
  <%= link_to "Back to hotel groups", hotel_groups_path %>
</div>

app/views/hotel_groups/index.html.erb
<%= link_to "New hotel group", new_hotel_group_path, class: "btn btn-success btn-sm pull-right" %>

<h1>Hotel groups</h1>
<div id="hotel_groups">
  <% @hotel_groups.each do |hotel_group| %>
    <%= render hotel_group %>
    <p>
      <%= link_to "Show this hotel group", hotel_group, class: "btn btn-warning btn-sm" %>
    </p>
  <% end %>
</div>

app/views/hotel_groups/show.html.erb
<%= render @hotel_group %>

<div>
  <%= link_to "Edit this hotel group", edit_hotel_group_path(@hotel_group) %> |
  <%= link_to "Back to hotel groups", hotel_groups_path %>

  <%= button_to "Destroy this hotel group", @hotel_group, method: :delete %>
</div>

app/views/hotels/_form.html.erb
<%= simple_form_for(@hotel) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Hotel Name') %>
  </div>
  <hr style="border: 1px solid;">
  <div class='builder'>
    <%= f.simple_fields_for :rooms do |builder| %>
          <%= render 'room', f: builder %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= link_to_add_association('Add room', f, :rooms, class: "btn btn-warning btn-sm") %>
  </div>
  <hr>
  <div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-lg pull-right" %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id @hotel %>">
  <p>
    <strong>Name:</strong>
    <%= @hotel.name %>
  </p>
  <p>
    <strong>Rooms:</strong>
    <% @hotel.rooms.each do |room| %>
    <%= room.room_no %>
    <% end %>
  </p>

</div>

app/views/hotels/_room.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-12">
      <div class="full-height-scroll">
        <div class="table-responsive">
          <table class="table table-striped" style="margin-bottom: 0;">
            <thead>
            <tr class="table-head">
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field(:room_no, required: true, class: "form-control", placeholder: 'Room No.') %></td>
                <td><%= link_to_remove_association "Remove Room", f, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hotels/_room_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-12">
      <div class="full-height-scroll">
        <div class="table-responsive">
          <table class="table table-striped" style="margin-bottom: 0;">
            <thead>
            <tr class="table-head">
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field(:room_no, required: true, class: "form-control", placeholder: 'Room No') %></td>
                <td><%= link_to_remove_association "Remove Room", f, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotel", hotels_path %>
</div>

app/views/hotels/index.html.erb
<h1>Hotels</h1>

<div id="hotels">
  <% @hotels.each do |hotel| %>
    <%= render hotel %>
    <p>
      <%= link_to "Show this hotel", hotel %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="text-center">Add New Hotel</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/hotels/remove_html.erb
<tr class="nested-fields">
  <td>
    <%= link_to_remove_association "remove hotel", f, class: 'btn btn-primary btn-xs' %>
  </td>
  <td><%= f.input :name, label: false %></td>
</tr>

app/views/hotels/show.html.erb
<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="col-lg-12">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Room Number') %>
  </div>
  <hr style="border: 1px solid;">
  <div class='builder'>
    <%= f.simple_fields_for :hotels do |builder| %>
          <%= render 'hotel', f: builder %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= link_to_add_association('Add Room', f, :hotels, class: "btn btn-warning btn-sm") %>
  </div>
  <hr>
  <div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-lg pull-right" %>
  </div>
<% end %>

app/views/rooms/_hotel.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-12">
      <div class="full-height-scroll">
        <div class="table-responsive">
          <table class="table table-striped" style="margin-bottom: 0;">
            <thead>
            <tr class="table-head">
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Room Number') %></td>
                <td><%= link_to_remove_association "Remove Hotel", f, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_hotel_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-12">
      <div class="full-height-scroll">
        <div class="table-responsive">
          <table class="table table-striped" style="margin-bottom: 0;">
            <thead>
            <tr class="table-head">
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field(:name, required: true, class: "form-control", placeholder: 'Room Number') %></td>
                <td><%= link_to_remove_association "Remove Hotel", f, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>
  <p>
    <strong>Hotels:</strong>
    <% room.hotels.each do |hotel| %>
    <%= hotel.name %>
    <% end %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this hotel group", @room %> |
  <%= link_to "Back to hotel groups", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotel groups</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this hotel group", room %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel group", new_room_path %>

app/views/rooms/new.html.erb
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="text-center">Add New Hotel Group</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/rooms/remove_html.erb
<tr class="nested-fields">
  <td>
    <%= link_to_remove_association "remove hotel", f, class: 'btn btn-primary btn-xs' %>
  </td>
  <td><%= f.input :description, label: false %></td>
  <td><%= f.input :done, label: false %></td>
</tr>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this hotel group", edit_room_path(@room) %> |
  <%= link_to "Back to hotel groups", room_path %>

  <%= button_to "Destroy this hotel group", @room, method: :delete %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark btn btn-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Hotel Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to t('navigation.sign_out'), destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% else %>
            <%= button_to 'Sign In', new_user_session_path, class: ' btn btn-secondary' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>